version: '3'

services:
  warmagednode0:
    container_name: warmagednode0
    image: "warmagezone/localnetnode"
    ports:
      - "26656-26657:26656-26657"
      - "8545-8546:8545-8546"
      - "9090-9091:9090-9091"
      - "1317:1317"
    environment:
      - ID=0
      - LOG=${LOG:-warmaged.log}
    volumes:
      - ./build:/warmage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  warmagednode1:
    container_name: warmagednode1
    image: "warmagezone/localnetnode"
    ports:
      - "26659-26660:26656-26657"
      - "8547-8548:8545-8546"
    environment:
      - ID=1
      - LOG=${LOG:-warmaged.log}
    volumes:
      - ./build:/warmage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  warmagednode2:
    container_name: warmagednode2
    image: "warmagezone/localnetnode"
    environment:
      - ID=2
      - LOG=${LOG:-warmaged.log}
    ports:
      - "26661-26662:26656-26657"
      - "8549-8550:8545-8546"
    volumes:
      - ./build:/warmage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  warmagednode3:
    container_name: warmagednode3
    image: "warmagezone/localnetnode"
    environment:
      - ID=3
      - LOG=${LOG:-warmaged.log}
    ports:
      - "26663-26664:26656-26657"
      - "8551-8552:8545-8546"
    volumes:
      - ./build:/warmage:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
