version: '3'

services:
  magenode0:
    container_name: magenode0
    image: warmage-sports/warmage:latest
    ports:
    - "26656-26657:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node0 && mage start --home mage'
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  magenode1:
    container_name: magenode1
    image: warmage-sports/warmage:latest
    ports:
    - "26659-26660:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node1 && mage start --home mage'
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  magenode2:
    container_name: magenode2
    image: warmage-sports/warmage:latest
    ports:
    - "26661-26662:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node2 && mage start --home mage'
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  magenode3:
    container_name: magenode3
    image: warmage-sports/warmage:latest
    ports:
    - "26663-26664:26656-26657"
    volumes:
    - ./build:/home
    command: /bin/sh -c 'cd /home/nodecluster/node3 && mage start --home mage'
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
